dim = 10
n_samples = 1000
n_reps = 10
skip_reps = 0
seed = 0
print_vectors = 1
n_iterations = 20000
lr = 0.001
verbose = 0
methods = "IRM"
alpha = 0.05
env_list = "3.5,.2,2.,5.,6.,.476,1.618033988749,.1"
setup_sem = "chain"
setup_ones = 1
setup_hidden = 1
setup_hetero = 1
setup_scramble = 1
n_threads = 8
irm_epoch_size = 50
irm_cuda = false
dump_config = true
