dim = 10
n_samples = 1000
n_reps = 10
skip_reps = 0
seed = 0
print_vectors = 1
n_iterations = 20000
lr = 0.001
verbose = 0
methods = "ERM,ICP,IRM"
alpha = 0.05
env_list = ".2,2.,5."
setup_sem = "chain"
setup_ones = 1
setup_hidden = 0
setup_hetero = 0
setup_scramble = 0
n_threads = 16
irm_epoch_size = 100
irm_cuda = false
dump_config = true
